# Generated by Django 5.1.5 on 2025-04-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizer',
            name='events',
            field=models.IntegerField(default=0),
        ),
    ]
