# Generated by Django 5.1.5 on 2025-01-17 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.organizer'),
        ),
    ]
