# Generated by Django 5.1.5 on 2025-04-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_invitelink_was_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='was_created',
        ),
    ]
