# Generated by Django 5.1.5 on 2025-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic')], default='classic', max_length=10),
        ),
    ]
