# Generated by Django 5.1.5 on 2025-04-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_invitelink_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
