# Generated by Django 5.1.5 on 2025-04-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
