# Generated by Django 5.1.5 on 2025-04-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_invitelink_was_created'),
        ('event', '0008_remove_location_name_alter_event_title'),
    ]

    operations = [
    ]
