# Generated by Django 5.1.5 on 2025-04-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_event_image_event_image_url'),
        ('ticket', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_created', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('status', models.TextField(choices=[('checked_in', 'Checked In'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='ongoing')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_events', to='event.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_events', to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
