# Generated by Django 5.1.5 on 2025-01-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_created', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('expired', 'Expired'), ('stub', 'Stub')], max_length=12, null=True)),
            ],
        ),
    ]
