# Generated by Django 5.1.5 on 2025-01-17 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.guest'),
        ),
    ]
